---
- name: Prepare ArchLinux Distributions
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: ensure depencencies are installed
      ansible.builtin.raw: pacman -Sy --noconfirm python grep mkinitcpio
      changed_when: false
